# Generated by Django 5.0.1 on 2025-08-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price_range", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("starting_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_text", models.CharField(blank=True, max_length=100)),
                ("includes", models.JSONField(blank=True, default=list)),
                ("perfect_for", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("starting_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_text", models.CharField(blank=True, max_length=100)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("tagline", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("service_area", models.CharField(max_length=255)),
                ("hours_text", models.CharField(max_length=255)),
                ("cancellation_policy", models.TextField()),
                ("weather_policy", models.TextField()),
                ("heavy_policy", models.TextField()),
                ("guarantee_policy", models.TextField()),
                ("theme_bg", models.CharField(default="#1a1a1a", max_length=7)),
                ("theme_accent", models.CharField(default="#7B2A2A", max_length=7)),
            ],
        ),
    ]
